version: '3'

services:
  spring_boot_mysql_database:
    image: mysql
    container_name: spring_boot_mysql_database2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: demo_devacademy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - spring_boot_mysql_database_data:/var/lib/mysql


volumes:
  spring_boot_mysql_database_data:
